### ISSUE TITLE
[Feature] path string을 리턴해주는 함수가 필요합니다.

### ISSUE THREAD

**Issue by ddalpange** [riiid/urichk#4]
현재 히스토리를 바꿀 때`useNavigate***`을 쓰는데요. 이 함수는 내부적으로 path를 조합해서 next router에 push 해줍니다.

path를 바꿀 때 router를 조작하지 않고 Link 컴포넌트를 쓸 때가 있어서 이 때는 조합된 path가 필요한데요.

해당 작업을 편하게 할 수 있는 유틸함수가 코드젠에 추가됬으면 좋을 것 같습니다.

```
const path = getToeicPath('/forgot-password', { email: 'riiid@riiid.co' });

return <Link href={path}>비밀번호를 잊어버리셨나요?</Link>
```

**Comment by disjukr** [comment]
`useNavigate***` 함수에 어떤 옵션을 추가한다는 것인지 코드를 봐서는 잘 모르겠습니다.
인터페이스 변경을 제안하시는 거라면 기존 인터페이스는 어떻게 생겼고, 제안하고자 하시는 인터페이스는 무엇이 추가되거나 수정되는 것인지 구분해서 적어주시면 감사하겠습니다.

**Comment by ddalpange** [comment]
아 영작 어렵네요 한글로 쓸게요

**Comment by hyp3rflow** [comment]
@ddalpange 혹시 종찬님께서 말씀하신대로 추가로 설명해주실 수 있으실까용

**Comment by ddalpange** [comment]
> @ddalpange 혹시 종찬님께서 말씀하신대로 추가로 설명해주실 수 있으실까용

타입스크립트로 구현한 [PR](https://github.com/riiid/jarvis-portal/pull/445/files#diff-9d3f2b801edfadeb1e78ce183a58503ea76ef31d0101afb8e00885ab61233f5cR5-R10)인데 아래와 같은 함수를 얻고 싶었습니다.

**Comment by hyp3rflow** [comment]
아 지금은 next/router에 의존하는 방식이라면 next/link 처럼 의존성 없이 사용하기 위해 path가 뽑혔으면 좋겠다는 말씀이시군요

**Comment by hyp3rflow** [comment]
```typescript
import { encode } from "querystring";

export interface PathOptionTable {
  /**
   * Webview for resetting password of a user.
   */
  ["/webview/reset-password"]: {
    /**
     * Code sent via email.
     */
    token?: string | null;
    [key: string]: undefined | null | string | string[];
  };

  /*
   * Webview of detailed promotion
   */
  ["/webview/event/info/detail"]: {
    /**
     * Promotion ID
     */
    promotionId?: string | null;
    [key: string]: undefined | null | string | string[];
  };
}

export default function getToeicPath<Path extends keyof PathOptionTable>(
  path: Path,
  searchParams: PathOptionTable[Path]
): string {
  const query = searchParams ? "?" + encode(searchParams) : "";
  return path + query;
}
```
@ddalpange 요렇게 코드젠되면 어떨까요?

**Comment by ddalpange** [comment]
> ```typescript
> 
> import { encode } from "querystring";
> 
> 
> 
> export interface PathOptionTable {
> 
>   /**
> 
>    * Webview for resetting password of a user.
> 
>    */
> 
>   ["/webview/reset-password"]: {
> 
>     /**
> 
>      * Code sent via email.
> 
>      */
> 
>     token?: string | null;
> 
>     [key: string]: undefined | null | string | string[];
> 
>   };
> 
> 
> 
>   /*
> 
>    * Webview of detailed promotion
> 
>    */
> 
>   ["/webview/event/info/detail"]: {
> 
>     /**
> 
>      * Promotion ID
> 
>      */
> 
>     promotionId?: string | null;
> 
>     [key: string]: undefined | null | string | string[];
> 
>   };
> 
> }
> 
> 
> 
> export default function getToeicPath<Path extends keyof PathOptionTable>(
> 
>   path: Path,
> 
>   searchParams: PathOptionTable[Path]
> 
> ): string {
> 
>   const query = searchParams ? "?" + encode(searchParams) : "";
> 
>   return path + query;
> 
> }
> 
> ```
> 
> @ddalpange 요렇게 코드젠되면 어떨까요?

넹 제가 원하던 것입니당
